#!/usr/bin/env python3
"""Turn a flat binary into a Verilog ROM built from Gowin pROM primitives.

This is what the IP Core Generator does for a "pROM" core, done here so
that a ROM image can be regenerated without the IDE: one pROM primitive
holds 1024 x 16 (64 INIT_RAM_xx parameters of 256 bits, word 0 in the
low 16 bits of INIT_RAM_00 - the layout read off fdd/ip/rawtr_prom/
rawtr_prom.v, whose MFM sync bytes A1A1 A1FE come out in address order
only that way round), the address is left-aligned in AD[13:4] for a
16-bit width, and blocks are picked by the address bits above 10 with
a registered selector, since the pROM output appears one clock after
its address.  Little-endian words, as a PDP-11 stores them.

  bin2prom.py in.bin out.v -m module_name
"""
import argparse, struct, sys

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("inp"); ap.add_argument("out")
    ap.add_argument("-m", "--module", required=True)
    a = ap.parse_args()
    data = open(a.inp, "rb").read()
    if len(data) % 2: data += b"\0"
    words = list(struct.unpack("<%dH" % (len(data)//2), data))
    nblk = (len(words) + 1023) // 1024
    abits = max(10, (nblk - 1).bit_length() + 10)
    words += [0] * (nblk * 1024 - len(words))
    o = []
    o.append("// Generated by tools/bin2prom.py from %s - do not edit.\n" % a.inp)
    o.append("// %d words in %d pROM blocks of 1024 x 16.\n" % (len(data)//2, nblk))
    o.append("module %s (dout, clk, ce, reset, ad);\n" % a.module)
    o.append("output [15:0] dout;\ninput clk;\ninput ce;\ninput reset;\ninput [%d:0] ad;\n" % (abits-1))
    o.append("wire gw_gnd = 1'b0;\n")
    for b in range(nblk):
        o.append("wire [31:0] do_%d;\n" % b)
    if nblk > 1:
        o.append("reg [%d:0] sel = 0;\nalways @(posedge clk) if (ce) sel <= ad[%d:10];\n" % (abits-11, abits-1))
        o.append("assign dout = " + " ".join("sel == %d ? do_%d[15:0] :" % (b, b) for b in range(nblk)) + " 16'd0;\n")
    else:
        o.append("assign dout = do_0[15:0];\n")
    for b in range(nblk):
        o.append("pROM blk_%d (\n    .DO(do_%d),\n    .CLK(clk),\n    .OCE(gw_gnd),\n    .CE(ce),\n    .RESET(reset),\n    .AD({ad[9:0],gw_gnd,gw_gnd,gw_gnd,gw_gnd})\n);\n" % (b, b))
        o.append("defparam blk_%d.READ_MODE = 1'b0;\ndefparam blk_%d.BIT_WIDTH = 16;\ndefparam blk_%d.RESET_MODE = \"SYNC\";\n" % (b, b, b))
        for p in range(64):
            chunk = words[b*1024 + p*16 : b*1024 + p*16 + 16]
            hexs = "".join("%04X" % w for w in reversed(chunk))
            o.append("defparam blk_%d.INIT_RAM_%02X = 256'h%s;\n" % (b, p, hexs))
    o.append("endmodule\n")
    open(a.out, "w").write("".join(o))
    print("%s: %d words, %d blocks, %d address bits" % (a.out, len(data)//2, nblk, abits))

if __name__ == "__main__":
    main()
