#!/usr/bin/env python3
"""Emit a gw_sh Tcl script that builds the bitstream, from the .gprj.

The Gowin IDE keeps what to build in tang/test003.gprj, and its headless
shell (gw_sh) wants the same thing as Tcl.  Generating one from the other
means the command-line build and the IDE build can never disagree about
the file list - which is the same reason tools/srcs.py exists.

The options come from tang/impl/gwsynthesis/test003.prj, which is what the
IDE last wrote:  top module `top`, SystemVerilog 2017 (ay/ym2149.sv needs
it), global_freq 100, ram_rw_check off.

  gowin_tcl.py > tang/build.tcl   then: cd tang && gw_sh build.tcl

Options, for building this core out of its tree (../tang-ultima does,
one flash slot per machine):

  --abs                   absolute source paths, so the Tcl can run from
                          any directory (gw_sh writes impl/ under its cwd)
  --multiboot-addr ADDR   the SPI flash address of the NEXT image, into
                          the bitstream header (Gowin MultiBoot, UG290
                          7.5.4): what the FPGA loads when top.v pulses
                          RECONFIG_N on SYS command 9.  4 KB aligned.
                          Default 0 - the image reloads itself.
  --loading-rate MHZ      the MSPI clock the FPGA reads the flash at
                          (Gowin's default is 2.5; a 907 KB image takes
                          about 3 s at that).  Left alone unless given.
"""

import os
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GPRJ = os.path.join(ROOT, "tang", "test003.gprj")

# .gprj file type -> the -type gw_sh wants
KIND = {
    "file.verilog": "verilog",
    "file.vhdl": "vhdl",
    "file.cst": "cst",
    "file.sdc": "sdc",
}


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--abs", action="store_true")
    ap.add_argument("--multiboot-addr", default=None)
    ap.add_argument("--loading-rate", default=None)
    args = ap.parse_args()
    tangdir = os.path.dirname(GPRJ)

    tree = ET.parse(GPRJ)
    root = tree.getroot()

    dev = root.iter("Device").__next__()
    name, pn = dev.get("name"), dev.get("pn")

    out = [
        "# Generated by tools/gowin_tcl.py - do not edit, regenerate.",
        "# Run from the tang/ directory:  gw_sh build.tcl",
        "",
        f"set_device -name {name} {pn}",
        "",
    ]

    for f in root.iter("File"):
        if f.get("enable") != "1":
            continue
        kind = KIND.get(f.get("type"))
        if kind is None:
            print(f"gowin_tcl.py: skipping {f.get('path')} "
                  f"({f.get('type')})", file=sys.stderr)
            continue
        path = f.get("path")
        if args.abs:
            path = os.path.abspath(os.path.join(tangdir, path))
        out.append(f'add_file -type {kind} "{path}"')

    out += [
        "",
        "set_option -top_module top",
        "set_option -verilog_std sysv2017",
        "set_option -global_freq 100.000",
        # The IDE's .prj calls this ram_rw_check; gw_sh in V1.9.11 calls it
        # rw_check_on_ram.  Same setting, and it is load-bearing: several
        # of these BSRAMs are read and written on the same cycle.
        "set_option -rw_check_on_ram 0",
    ]

    # Dual-purpose pins.  The IDE keeps these in its own process config, and
    # they are not optional here: HP_BCK/HP_WS/HP_DIN are on 56/55/54, which
    # are the SSPI pins, and without freeing them placement fails outright
    # with PR2017.  Read them rather than hard-code them, so a change made
    # in the IDE carries over.
    cfgp = os.path.join(ROOT, "tang", "impl", "test003_process_config.json")
    dual = [("SSPI", "use_sspi_as_gpio"), ("MSPI", "use_mspi_as_gpio"),
            ("READY", "use_ready_as_gpio"), ("DONE", "use_done_as_gpio"),
            ("RECONFIG_N", "use_reconfign_as_gpio"),
            ("CPU", "use_cpu_as_gpio"), ("I2C", "use_i2c_as_gpio"),
            ("JTAG", "use_jtag_as_gpio")]
    if os.path.exists(cfgp):
        import json
        cfg = json.load(open(cfgp))
        for key, opt in dual:
            if cfg.get(key) is True:
                out.append(f"set_option -{opt} 1")
        # The IDE's process config also asks the router to fix hold
        # violations; say so here too, or the headless flow leaves the
        # coincident-edge crossings (clk4/clk_25, clkram/clk_25) a tenth
        # of a nanosecond short.  Sep 2026.
        if cfg.get("Correct_Hold_Violation") is True:
            out.append("set_option -correct_hold_violation 1")
    else:
        print(f"gowin_tcl.py: no {cfgp}, dual-purpose pins left alone",
              file=sys.stderr)

    # MultiBoot: the next image's flash address goes into the bitstream
    # header (//MultiBootSPIAddr in the .fs); RECONFIG_N low loads it.
    if args.multiboot_addr is not None:
        addr = int(args.multiboot_addr, 0)
        if addr & 0xfff:
            sys.exit("gowin_tcl.py: --multiboot-addr must be 4 KB aligned")
        out.append("set_option -multi_boot 1")
        out.append(f"set_option -multiboot_spi_flash_address {addr:08x}")   # bare hex: the tool adds the 0x itself
    if args.loading_rate is not None:
        out.append(f"set_option -loading_rate {args.loading_rate}")

    out += [
        "set_option -output_base_name test003",
        "",
        "run all",
    ]
    print("\n".join(out))


if __name__ == "__main__":
    main()
