#!/usr/bin/env python3
"""Emit a gw_sh Tcl script that builds the bitstream, from the .gprj.

The Gowin IDE keeps what to build in tang/test003.gprj, and its headless
shell (gw_sh) wants the same thing as Tcl.  Generating one from the other
means the command-line build and the IDE build can never disagree about
the file list - which is the same reason tools/srcs.py exists.

The options come from tang/impl/gwsynthesis/test003.prj, which is what the
IDE last wrote:  top module `top`, SystemVerilog 2017 (ay/ym2149.sv needs
it), global_freq 100, ram_rw_check off.

  gowin_tcl.py > tang/build.tcl   then: cd tang && gw_sh build.tcl
"""

import os
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GPRJ = os.path.join(ROOT, "tang", "test003.gprj")

# .gprj file type -> the -type gw_sh wants
KIND = {
    "file.verilog": "verilog",
    "file.vhdl": "vhdl",
    "file.cst": "cst",
    "file.sdc": "sdc",
}


def main():
    tree = ET.parse(GPRJ)
    root = tree.getroot()

    dev = root.iter("Device").__next__()
    name, pn = dev.get("name"), dev.get("pn")

    out = [
        "# Generated by tools/gowin_tcl.py - do not edit, regenerate.",
        "# Run from the tang/ directory:  gw_sh build.tcl",
        "",
        f"set_device -name {name} {pn}",
        "",
    ]

    for f in root.iter("File"):
        if f.get("enable") != "1":
            continue
        kind = KIND.get(f.get("type"))
        if kind is None:
            print(f"gowin_tcl.py: skipping {f.get('path')} "
                  f"({f.get('type')})", file=sys.stderr)
            continue
        out.append(f'add_file -type {kind} "{f.get("path")}"')

    out += [
        "",
        "set_option -top_module top",
        "set_option -verilog_std sysv2017",
        "set_option -global_freq 100.000",
        # The IDE's .prj calls this ram_rw_check; gw_sh in V1.9.11 calls it
        # rw_check_on_ram.  Same setting, and it is load-bearing: several
        # of these BSRAMs are read and written on the same cycle.
        "set_option -rw_check_on_ram 0",
    ]

    # Dual-purpose pins.  The IDE keeps these in its own process config, and
    # they are not optional here: HP_BCK/HP_WS/HP_DIN are on 56/55/54, which
    # are the SSPI pins, and without freeing them placement fails outright
    # with PR2017.  Read them rather than hard-code them, so a change made
    # in the IDE carries over.
    cfgp = os.path.join(ROOT, "tang", "impl", "test003_process_config.json")
    dual = [("SSPI", "use_sspi_as_gpio"), ("MSPI", "use_mspi_as_gpio"),
            ("READY", "use_ready_as_gpio"), ("DONE", "use_done_as_gpio"),
            ("RECONFIG_N", "use_reconfign_as_gpio"),
            ("CPU", "use_cpu_as_gpio"), ("I2C", "use_i2c_as_gpio"),
            ("JTAG", "use_jtag_as_gpio")]
    if os.path.exists(cfgp):
        import json
        cfg = json.load(open(cfgp))
        for key, opt in dual:
            if cfg.get(key) is True:
                out.append(f"set_option -{opt} 1")
    else:
        print(f"gowin_tcl.py: no {cfgp}, dual-purpose pins left alone",
              file=sys.stderr)

    out += [
        "set_option -output_base_name test003",
        "",
        "run all",
    ]
    print("\n".join(out))


if __name__ == "__main__":
    main()
