# Generated by tools/gowin_tcl.py - do not edit, regenerate.
# Run from the tang/ directory:  gw_sh build.tcl

set_device -name GW2AR-18C GW2AR-LV18QN88C8/I7

add_file -type verilog "src/aberrant.v"
add_file -type verilog "src/covox.v"
add_file -type verilog "src/audio.v"
add_file -type verilog "src/ay/ym2149.sv"
add_file -type verilog "src/cpu.v"
add_file -type verilog "src/fdd/fdd4.v"
add_file -type verilog "src/fdd/ip/rawtr_prom/rawtr_prom.v"
add_file -type verilog "src/ide/ide.v"
add_file -type verilog "src/ide/ide_rom.v"
add_file -type verilog "src/ide/sd_arbiter.v"
add_file -type verilog "src/ip/dbufsec16/dbufsec16.v"
add_file -type verilog "src/ip/fifo_audio/fifo_audio.v"
add_file -type verilog "src/ip/rom208/rom208.v"
add_file -type verilog "src/ip/sdbuf_sdpb/sdbuf_sdpb.v"
add_file -type verilog "src/ip/sys_rpll/sys_rpll.v"
add_file -type verilog "src/ip/uartfifo/uartfifo.v"
add_file -type verilog "src/hdmi/hdmi_packet.v"
add_file -type verilog "src/hdmi/hdmi_serdes.v"
add_file -type verilog "src/hdmi/hdmi_tx.v"
add_file -type verilog "src/hdmi/tmds_channel.v"
add_file -type verilog "src/mister/hid.v"
add_file -type verilog "src/mister/mcu_spi.v"
add_file -type verilog "src/mister/osd_u8g2.v"
add_file -type verilog "src/mister/sd_card.v"
add_file -type verilog "src/mister/sd_rw.v"
add_file -type verilog "src/mister/sdcmd_ctrl.v"
add_file -type verilog "src/mister/sector_dpram.v"
add_file -type verilog "src/mister/sysctrl.v"
add_file -type verilog "src/mkcolorreg.v"
add_file -type verilog "src/ppu.v"
add_file -type verilog "src/sdram2.v"
add_file -type verilog "src/top.v"
add_file -type verilog "src/uart/uart_rx.v"
add_file -type verilog "src/uart/uart_tx.v"
add_file -type verilog "src/vp1-128fdd.v"
add_file -type verilog "src/vp1_120.v"
add_file -type verilog "src/vp65.v"
add_file -type verilog "src/wm2wb/vm2_plm.v"
add_file -type verilog "src/wm2wb/vm2_wb.v"
add_file -type verilog "src/wmrst.v"
add_file -type verilog "src/xm2-01.v"
add_file -type cst "src/test003.cst"
add_file -type sdc "src/test003.sdc"

set_option -top_module top
set_option -verilog_std sysv2017
set_option -global_freq 100.000
set_option -rw_check_on_ram 0
set_option -use_sspi_as_gpio 1
set_option -correct_hold_violation 1
set_option -output_base_name test003

run all
